### ISSUE TITLE
There is no dispatch in Execute

### ISSUE THREAD

**Issue by 11111000000** [mocoding-software/redux-automata#3]
```
...
export function EffectShopInit(dispatch) {
    log(dispatch)
    new Promise.all([
        dispatch(rest.actions.shopCategories()),
        dispatch(rest.actions.shopSubCategories({ id: TOP_PRODUCTS })),
        dispatch(rest.actions.shopProducts({ id: TOP_PRODUCTS }))
    ]).then(() => dispatch(ActionShopDataLoaded))
}

automata
    .in(StateUnInitialized)
       .on(ActionShopInit)
         .execute(EffectShopInit)
         .goTo(StateLoadData)
...
```
logs : `undefined`

**Comment by 11111000000** [comment]
Ant when I try to use external `dispatch`, from same `store`, then:
```
createStore.js?6413:160 Uncaught Error: Reducers may not dispatch actions.
```

**Comment by offbeatful** [comment]
Thanks for the issues. To better troubleshoot your issues I need a little bit more information:
- Could you please confirm that you are using the latest version: 2.1.1 
- Also, please indicate what version of redux is used.
- Please confirm that automataMiddleware is added when composing the store. Redux.applyMiddleware(automataMiddleware)

**Comment by 11111000000** [comment]
- redux-automata 2.1.1
- redux 3.7.2
-
`middleware.js`:
```
import { applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import auth from 'modules/auth/effects';
import profile from 'modules/profile/effects';
import wallet from 'modules/wallet/effects';
import shop from 'modules/shop/effects';
import shopCart from 'modules/shop-cart/effects';
import analytics from 'modules/analytics/effects';
import terminal from 'modules/cap-terminal/effects';

import routing from 'modules/history/effects';
//import socket from 'modules/socket/effects';
import history from 'modules/history';
import { routerMiddleware } from 'react-router-redux';
const historyMiddleware = routerMiddleware(history);

export default applyMiddleware(
    analytics,
    thunk,
    auth,
    profile,
    wallet,
    shop,
    shopCart,
    historyMiddleware,
    routing,
    terminal
    //socket,
);
```
`store.js`:
```
/**
 * @fileOverview Хранилище Redux
 * @name store/index.js
 * @author CAP Team
 * @license All Rights Reserved by "Cyber Arena Pro" Team
 */

import { createStore, compose } from 'redux'
import { persistStore } from 'redux-persist'
import middleware from './middleware'
import reducer from './reducer'

const composeEnhancers =
  typeof window === 'object' &&
  window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
      window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
}) : compose;

export const store = createStore(reducer, composeEnhancers(middleware))

export const persistor = persistStore(store)

export function value(key) {
    return key.split('.')
        .reduce((o, x) => (
            (typeof o == 'undefined' || o === null) ? o : o[x]
        ), store.getState())
}

export function value2(key) {
    return key.split('.').reduce(function(o, x) {
        return (typeof o == 'undefined' || o === null) ? o : o[x]
    })
}
```

**Comment by 11111000000** [comment]
but where is documentation about `automataMiddleware`

**Comment by offbeatful** [comment]
It is missing in documentaion. We will add this. Please refer to one of the examples. Basically you will need to import ‘’’automataMiddleware’’’ and add it yo your middlware.js file applyMiddlware function. Please let me know whenever it works or not.

**Comment by 11111000000** [comment]
all works, thanks you! Update docs and we can close that.

**Comment by 11111000000** [comment]
And, already, how to use action parameters in `execute` handler?
In any normal middleware we have `({dispatch,getState}, { ...payload })`

**Comment by offbeatful** [comment]
Execute handler has second parameter and it is action parameter.
That is in documentation.

**Comment by 11111000000** [comment]
sorry

**Comment by 11111000000** [comment]
it works, but we need standart middleware approach `({dispatch,getState}, { ...payload })`, like I  mention before. Now I need external call to `store.getState()`

**Comment by offbeatful** [comment]
How about adding a third parameter which will be getState method?

**Comment by 11111000000** [comment]
Any troubles with right middleware logic? Old code may depend with old version of automata

**Comment by offbeatful** [comment]
Yes. We would like to keep a backward compatibility. Also execute method is not meant to be the same as middleware.

**Comment by 11111000000** [comment]
Ok

**Comment by artalar** [comment]
One of conclusions, it pass `dispatch` function with `getState` and `dispatch` parameters. In this case u don`t broke compatibility and get new API features.
And in next major version u can pass plain object with needed properties.

**Comment by offbeatful** [comment]
@artalar thanks for suggestion! getState and dispatch were added to dispatch function to maintain backward compatibility.

Please note that getState will return current automata state and not the full tree state. Please reply back if it is still an issue.
