### ISSUE TITLE
multiple goTo(...).goTo(...)

### ISSUE THREAD

**Issue by 11111000000** [mocoding-software/redux-automata#4]
like 
```
    .in(StateLoadData)
        .on(ActionDataLoaded)
            .goTo(StateInitialized)
            .goTo(StateWait)
```
where
```
const StateInitialized  = automata.state(
    'Магазин запущен',
    (state) => ({ ...state, loading: false, initialized: true }))

const StateWait = automata.state(
    'Магазин ожидает',
    (state) => (state))
```

now it thrown
`model.js?893e:46 Uncaught TypeError: automata.in(...).on(...).execute(...).goTo(...).in(...).on(...).goTo(...).goTo is not a function`

**Comment by offbeatful** [comment]
Unfortunately, the state machine can’t be in two states simultaneously. goTo is the last method in configuration chain for transition so it is not defined. (You may have only one goTo) method. What is yhe intent of you use case? Should yhe state machine end in StateWait state?

Since the state is intended to reflect current UI state I would suggest to have distinct assignment for state. For example:
InitialState - nothing
Loading - spinner (exexute to fetch data)
Loaded - data displayed. (Waiting for next actions from users)

**Comment by 11111000000** [comment]
Ok, I have some products, each can be in three states: selected/unselected/added.
But I have only ProductsList State Machine (no separate State Machine for each Product, but I want to maintain one for list)
```
....
const StateUnInitialized  = automata.state(
    'Магазин не запущен',
    (state) => (defaultState))

const StateLoadData = automata.state(
    'Магазин загружает данные',
    (state) => ({ ...state, loading: true }))

const StateWait = automata.state(
    'Магазин ожидает',
    (state) => ({ ...state, loading: false, initialized: true, selected: {} }))

const StateProductsSelected = automata.state(
    'Выбран один или более продуктов',
    (state, { data }) => ({
        ...state,
        selected: { ...state.selected,
                    [data.id]: !state.selected[data.id] } }))

....
automata
    .in(StateUnInitialized)
       .on(ActionInit)
         .execute(EffectInit)
         .goTo(StateLoadData)

    .in(StateLoadData)
        .on(ActionDataLoaded)
            .goTo(StateWait)

    .in(StateWait).or(StateProductsSelected)
        .on(ActionProductsItemClick)
            .goTo(StateProductsSelected)

    .in(StateProductsSelected)
        .on(ActionAddSelected)
            .goTo(StateWait)
```
When user click on product - then it selected and checked in `selected`.And now we are in `StateProductsSelected`. But when user click's again on the same product, then I want to unselect It, and this logic is ` selected[data.id] = !state.selected[data.id] `, but how to determine (inside action) if now we don't have any selected products, and transition to `StateWait` then?

**Comment by 11111000000** [comment]
What is the most common and suitable ES/Automata patterns to conditionally switch the Automata state we should use here? How to do that "before" or "after" state switch? (i.e. any redux middleware or redux-thunk) How about to have some "rehydration" conditional Effect with ActionUpdate, to set correct atomata State from some (chained with automata semantics or external) conditions?

**Comment by offbeatful** [comment]
Correct. The state transitions are constant. If you need to execute something that requires additional dynamic check (and if it is not possible to represent this check as automation) then execute method should be used.
Execute method has the following declaration: 
```ts
type TransitionMethod<TPayload extends ActionPayload = undefined>
    = (dispatch: Redux.Dispatch<any>, arg: TPayload) => void;
```
you may pass a parameter and then invoke any dispatch method from that.
Also, you always has access to automata.current. which is the current state (a copy from store). That is not very reliable way but there is a plan to move it to Execute as getState method.

**Comment by offbeatful** [comment]
If you case is to have a product list that is loading and then allow users to select/deselect items in list then I would propose the following states and transitions:

1. Idle - nothing is loaded
2. Loading - loading data
3. Loaded - data was loaded
4. Changed - data was selected/unselected

```ts
in(Idle)
    .on(Load)
        .execute(LoadData)
        .goTo(Loading)
    .on(Loading)
        .on(DataLoaded)
        .goTo(Loaded)
    .on(Loaded)
    .or(Changed)
        .on(ChangeSelection)
            .goTo(Changed)
```

Optional to think about:
5. Submitting / Submitted - if you need to submit selected values back to the server or continue your workflow
6. Error - if something goes wrong when loading/submitting

**Comment by 11111000000** [comment]
Thank you! Very clear!
